"""
src/hazematching/data_prep.py
=============================
Prepares the Laparoscopy dataset for HazeMatching.
1. Splits into train, val, test (70/15/15)
2. Computes normalization statistics (mean/std) on the training set
3. Saves the statistics and injects them into hazematching.datasets.data_norm
"""

import os
import shutil
from pathlib import Path
import numpy as np
from PIL import Image
from tqdm import tqdm

from hazematching.datasets import data_norm

def compute_and_inject_stats(train_dir: Path):
    """
    Computes mean and std for clean and smoky images in the training set
    (converted to grayscale) and injects them into HazeMatching's data_norm.STATS.
    """
    clean_dir = train_dir / "clean"
    smoky_dir = train_dir / "smoky"
    
    clean_files = sorted([f for f in os.listdir(clean_dir) if f.endswith('.png')])
    
    print(f"Computing stats from {len(clean_files)} training images...")
    
    clean_means, clean_vars = [], []
    smoky_means, smoky_vars = [], []
    
    for f in tqdm(clean_files, desc="Stats"):
        # Load grayscale
        c_img = np.array(Image.open(clean_dir / f).convert('L'), dtype=np.float32)
        s_img = np.array(Image.open(smoky_dir / f).convert('L'), dtype=np.float32)
        
        clean_means.append(c_img.mean())
        clean_vars.append(c_img.var())
        
        smoky_means.append(s_img.mean())
        smoky_vars.append(s_img.var())
        
    # Aggregate (simplified calculation over dataset)
    c_mean = float(np.mean(clean_means))
    c_std = float(np.sqrt(np.mean(clean_vars)))
    
    s_mean = float(np.mean(smoky_means))
    s_std = float(np.sqrt(np.mean(smoky_vars)))
    
    print("\nComputed Statistics (Grayscale):")
    print(f"Clean (Ch 0): Mean = {c_mean:.4f}, Std = {c_std:.4f}")
    print(f"Smoky (Ch 1): Mean = {s_mean:.4f}, Std = {s_std:.4f}")
    
    # Inject into HazeMatching
    # Format: dataset: ([mean_ch0, mean_ch1], [std_ch0, std_ch1])
    data_norm.STATS["laparoscopy"] = ([c_mean, s_mean], [c_std, s_std])
    
    # Write to norm_stats.py so it can be imported later
    stats_file = Path(__file__).parent / "norm_stats.py"
    with open(stats_file, "w") as f:
        f.write('"""Auto-generated by data_prep.py"""\n')
        f.write(f'LAPAROSCOPY_STATS = ( [{c_mean}, {s_mean}], [{c_std}, {s_std}] )\n')
        f.write('\ndef inject_stats():\n')
        f.write('    from hazematching.datasets import data_norm\n')
        f.write('    data_norm.STATS["laparoscopy"] = LAPAROSCOPY_STATS\n')
        
    print(f"Saved stats to {stats_file}")


def prepare_dataset(src_dir: str, dest_dir: str, seed: int = 42):
    """
    Creates train/val/test splits by copying files.
    """
    np.random.seed(seed)
    
    src = Path(src_dir)
    dest = Path(dest_dir)
    
    clean_src = src / "clean"
    smoky_src = src / "smoky"
    
    files = sorted([f for f in os.listdir(clean_src) if f.endswith('.png')])
    np.random.shuffle(files)
    
    n = len(files)
    train_split = int(0.7 * n)
    val_split = int(0.85 * n)
    
    splits = {
        "train_crop": files[:train_split],
        "val_crop": files[train_split:val_split],
        "test": files[val_split:]
    }
    
    for split_name, split_files in splits.items():
        print(f"\nProcessing {split_name} ({len(split_files)} files)...")
        
        split_dest = dest / split_name
        (split_dest / "clean").mkdir(parents=True, exist_ok=True)
        (split_dest / "smoky").mkdir(parents=True, exist_ok=True)
        
        for f in tqdm(split_files, desc=split_name):
            shutil.copy2(clean_src / f, split_dest / "clean" / f)
            shutil.copy2(smoky_src / f, split_dest / "smoky" / f)
            
    # Compute stats from training set
    compute_and_inject_stats(dest / "train_crop")
    print("\nDataset preparation complete.")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Prepare dataset splits for HazeMatching")
    parser.add_argument("--src-dir", default="data_final", help="Source directory containing clean and smoky folders")
    parser.add_argument("--dest-dir", default="data/laparoscopy", help="Destination directory for splits")
    args = parser.parse_args()

    prepare_dataset(
        src_dir=args.src_dir,
        dest_dir=args.dest_dir
    )
