"""Auto-generated by data_prep.py"""
LAPAROSCOPY_STATS = ( [61.22509765625, 168.09014892578125], [63.07986831665039, 29.9714412689209] )

def inject_stats():
    from hazematching.datasets import data_norm
    data_norm.STATS["laparoscopy"] = LAPAROSCOPY_STATS
